### PR TITLE
Added optional configuration property <device-type-id> to iOS platform config

### PR DESCRIPTION
**Pull request by fabianwulf**
Usable as optional argument to define a target iOS simulator (iPhone/SDK versions).

"device-type-id" could be used to replace deprecated arguments --family and --sdk (as printed out by haxe compiler (3.2.0) each build).
## Usage inside duell_project.xml

<platform-config>
    <ios>
        <device-type-id value="com.apple.CoreSimulator.SimDeviceType.iPhone-5, 8.2"/>
    </ios>
</platform-config>

If omitted in the duell_project.xml the simulator would be "com.apple.CoreSimulator.SimDeviceType.iPhone-4s, 8.2".

A list of can be retrieved  by calling **ios-sim showdevicetypes** via command line.
At this point of time supported device types would be:
- com.apple.CoreSimulator.SimDeviceType.iPhone-4s, 7.1
- com.apple.CoreSimulator.SimDeviceType.iPhone-5, 7.1
- com.apple.CoreSimulator.SimDeviceType.iPhone-5s, 7.1
- com.apple.CoreSimulator.SimDeviceType.iPad-2, 7.1
- com.apple.CoreSimulator.SimDeviceType.iPad-Retina, 7.1
- com.apple.CoreSimulator.SimDeviceType.iPad-Air, 7.1
- com.apple.CoreSimulator.SimDeviceType.iPhone-4s, 8.1
- com.apple.CoreSimulator.SimDeviceType.iPhone-5, 8.1
- com.apple.CoreSimulator.SimDeviceType.iPhone-5s, 8.1
- com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus, 8.1
- com.apple.CoreSimulator.SimDeviceType.iPhone-6, 8.1
- com.apple.CoreSimulator.SimDeviceType.iPad-2, 8.1
- com.apple.CoreSimulator.SimDeviceType.iPad-Retina, 8.1
- com.apple.CoreSimulator.SimDeviceType.iPad-Air, 8.1
- com.apple.CoreSimulator.SimDeviceType.Resizable-iPhone, 8.1
- com.apple.CoreSimulator.SimDeviceType.Resizable-iPad, 8.1
- com.apple.CoreSimulator.SimDeviceType.iPhone-4s, 8.2
- com.apple.CoreSimulator.SimDeviceType.iPhone-5, 8.2
- com.apple.CoreSimulator.SimDeviceType.iPhone-5s, 8.2
- com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus, 8.2
- com.apple.CoreSimulator.SimDeviceType.iPhone-6, 8.2
- com.apple.CoreSimulator.SimDeviceType.iPad-2, 8.2
- com.apple.CoreSimulator.SimDeviceType.iPad-Retina, 8.2
- com.apple.CoreSimulator.SimDeviceType.iPad-Air, 8.2
- com.apple.CoreSimulator.SimDeviceType.Resizable-iPhone, 8.2
- com.apple.CoreSimulator.SimDeviceType.Resizable-iPad, 8.2

Note: It's very much possible that I forgot to cover all sorts of cases, so this plugin enhancement might be incomplete. If so please get back to me what the next steps would be to fix.
Cheers,
Fabian

### CODE REVIEW

**Comment by catdawg** [comment]
Great feature! Looks like the implementation is fine.

There is just one thing, can you add a command line parameter instead of a XML configuration (or maybe both? ) because this could be used in the CI to test on multiple devices per run. 

By parameter I mean something like:

duell build ios -simulator -devicetypeid "com.apple.CoreSimulator.SimDeviceType.iPad-Retina, 8.2"

**Comment by andreashanft** [comment]
Yes great feature indeed! I also agree that a command line parameter makes more sense than a XML config.

And if I could add a feature request, instead of the exact simulator ID string some convenience types would be nice, like:

duell build ios -simulator -simdevice ipad -> selects latest ipad
duell build ios -simulator -simdevice ipad -simos 7 -> selects latest os, eg 7.1.x 

thanks!

**Comment by catdawg** [comment]
For the simplification maybe we can just add:
iPhone-4s, 7.1
"com.apple.CoreSimulator.SimDeviceType." is redundant.

Also listing the possible devices on the -help would be nice.

**Comment by andreashanft** [comment]
Seeing this from a testing perspective, I can understand that you want to be able to select a very specific device.

My suggestion comes from the eyes of a game developer that for every day programming does not care about a specific device but only the device category and ease of use of the command. Meaning if I can use the command without remembering a specific device ID string or having to consult a MAN page it makes my everyday use of it faster and easier and my overall productivity higher ;)

**Comment by catdawg** [comment]
well, if @fabianwulf is fine with making that change. No problem then. 

Right now this is a feature needed for testing. XML doesn't work very well for that, so we need a build parameter. I'm fine with any way the parameter is done.

**Comment by fabianwulf** [comment]
Sorry for not having replied earlier! Seems I turned off email-notifications a while ago, so I read your comments just yet.. :) Anyway, thanks for your input!

Your suggestions are very welcome and I'll try my best to start implementing
- the device-type-id configurable via command line argument
- simplification of the identifier strings, e.g. omitting the redundant "com.apple.CoreSimulator.SimDeviceType."
- updating the help description to contain a list of available devices/sdks
  as soon as possible.

Also I like @andreashanft's idea to have a more convenient configuration for the command line arguments, i.e. "-simdevice ipad"  and/or "-simos 7", though I'd like to postpone this for now?!

**Comment by fabianwulf** [comment]
**Update**
Feature should work with command line arguments **-simdevice** and **-simos** from now on.

Also updated xml configuration so that <device-type-id> was replaced by <sim-device> and <sim-os>. 
**Note**: Xml configuration is currently overriding configuration via command line arguments as xml config is parsed after computing any cmd line args.

List of supported devices and OSs are displayed using the help commmand.

**Comment by catdawg** [comment]
Command line arguments should always take precedence over XML... But apart from that, it looks very nice!

**Comment by fabianwulf** [comment]
Thanks for your feedback, will have a look into that!

**Comment by nensanders** [comment]
Secret framework developer ;-)

**Comment by fabianwulf** [comment]
**Update**
The commit message says it all... :)

@nensanders : Totally forgot you are not in LiveOps mode already.... ;)

**Comment by catdawg** [comment]
Merged! thank you!

We will go into test mode for now on the feature. We can tag in a few days.

This means that you can test the new feature by putting on the XML <supports-build-plugin name="ios" version="master" />

We should tag in 1 or 2 days anyway.

**Comment by andreashanft** [comment]
Good work! Thanks! :+1:

**Pull request merged**
